# Generated by Django 3.1.7 on 2021-03-08 19:24

import common.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0005_accountlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CreditProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(verbose_name='Duration in months')),
                ('percent', models.FloatField(validators=[django.core.validators.MinValueValidator(0.99), django.core.validators.MaxValueValidator(100.0)], verbose_name='Percent')),
                ('active', models.BooleanField(default=True)),
                ('credit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.credittype')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.currency')),
            ],
        ),
        migrations.CreateModel(
            name='CreditContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=common.models.random_string, editable=False, max_length=9, verbose_name='Number')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('days_left', models.PositiveIntegerField(verbose_name='Days left')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('closed', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.client')),
                ('credit_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.creditprogram')),
                ('main_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_c', to='common.account')),
                ('percent_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percent_c', to='common.account')),
            ],
        ),
    ]
