# Generated by Django 3.1.7 on 2021-03-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcontract',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='credits'),
        ),
    ]
