# Generated by Django 3.1.7 on 2021-03-06 15:24

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20210306_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('suffix_number', models.CharField(default=common.models.random_string, editable=False, max_length=9, verbose_name='Number suffix')),
                ('code', models.CharField(choices=[('3014', '3014'), ('2400', '2400'), ('1010', '1010'), ('7327', ' 7327')], editable=False, max_length=4, verbose_name='Code')),
                ('activity', models.CharField(choices=[('active', 'active'), ('passive', 'passive'), ('active-passive', 'active-passive')], max_length=255, verbose_name='Activity')),
                ('debit', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Debit')),
                ('credit', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Credit')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Balance')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.client')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.currency')),
            ],
            options={
                'unique_together': {('created', 'code', 'suffix_number')},
            },
        ),
    ]
