# Generated by Django 3.1.7 on 2021-03-06 15:01

import common.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20210306_1801'),
        ('deposits', '0002_auto_20210304_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=common.models.random_string, editable=False, max_length=9, verbose_name='Number')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('days_left', models.PositiveIntegerField(verbose_name='Days left')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('closed', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.client')),
            ],
        ),
        migrations.CreateModel(
            name='DepositProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(verbose_name='Duration in months')),
                ('percent', models.FloatField(validators=[django.core.validators.MinValueValidator(0.99), django.core.validators.MaxValueValidator(100.0)], verbose_name='Percent')),
                ('active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.currency')),
                ('deposit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposits.deposittype')),
            ],
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='client',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='deposit_type',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.AddField(
            model_name='depositcontract',
            name='deposit_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposits.depositprogram'),
        ),
        migrations.AddField(
            model_name='depositcontract',
            name='main_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='common.account'),
        ),
        migrations.AddField(
            model_name='depositcontract',
            name='percent_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percent', to='common.account'),
        ),
    ]
